blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_list/create/', BlogCreateView.as_view(), name='blog_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from config.settings import STATIC_ROOT, STATIC_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    header = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='содержимое статьи')
    img = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    views = models.IntegerField(default=0, verbose_name='кол-во просмотров')
    date = models.DateTimeField(auto_now=True, verbose_name='дата публикации')

blog/views.py
from django.shortcuts import render
from django.views import generic
from blog.models import Blog
from django.urls import reverse_lazy


class BlogListView(generic.ListView):
    model = Blog


class BlogDetailView(generic.DetailView):
    model = Blog


class BlogCreateView(generic.CreateView):
    model = Blog
    fields = ('header', 'content', 'img')
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_form.html
{% extends 'main/base.html'%}

{% block content %}

        <form class="row" method="post">
            <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if client %}Сохранить{% else %} Создать {% endif %}">

                <div class="card-footer">
                    <a href="{% url 'blog:blog_list' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        <div class="col-6">
            <div class="card">
               <div class="card-header">
                   Блог
               </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html'%}
{% load mediapath %}
{% block content %}

    <div class="col-12">
        <a href="{% url 'blog:blog_create' %}" class="btn btn-primary m-2">Создать запись</a>
    </div>
    {% for blog in blog_list %}
        {% include 'blog/includes/inc_blog_card.html' %}
    {% endfor %}

{% endblock %}