blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_list/create/', BlogCreateView.as_view(), name='blog_create'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from config.settings import STATIC_ROOT, STATIC_URL


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from django.views.decorators.cache import cache_page
from main.views import HomeView, MailingListView, MailingCreateView, MailingDeleteView, MailingDetailView, \
    MailingUpdateView, ClientListView, ClientCreateView, ClientDeleteView, ClientDetailView, ClientUpdateView, \
    MessageUpdateView, MessageDetailView, MessageDeleteView, MessageCreateView, MessageListView, deactive_mailing

app_name = MainConfig.name

urlpatterns = [

    path('', cache_page(60)(HomeView.as_view()), name='homepage'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_list/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_list/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing_list/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_list/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('client_list/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client_list/create/', ClientCreateView.as_view(), name='client_create'),
    path('client_list/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client_list/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_list/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_list/create/', MessageCreateView.as_view(), name='message_create'),
    path('message_list/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('message_list/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message_list/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('detail/deactive_mailing/<int:pk>/', deactive_mailing, name='deactive_mailing'),

]

main/models.py
from datetime import datetime, date

from django.db import models

import users.models

NULLABLE = {'blank': True, 'null': True}


class Message(models.Model):
    # Сообщение в рассылке
    theme = models.CharField(max_length=150, verbose_name='Тема')
    content = models.TextField(max_length=5000, verbose_name='Тело сообщения')

    def __str__(self):
        return f'{self.theme}'

    class Meta:
        verbose_name = 'сообщение рассылки'
        verbose_name_plural = 'сообщения рассылки'
        ordering = ('mailing',)

class Client(models.Model):
    # Клиенты для рассылки
    email = models.EmailField(unique=True, verbose_name='почта')
    author = models.ForeignKey(users.models.User, on_delete=models.CASCADE, verbose_name='автор', **NULLABLE)

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ('email',)



class Mailing(models.Model):

    FREQUENCY_CHOICES = [
        ('daily', 'Ежедневно'),
        ('weekly', 'Еженедельно'),
        ('monthly', 'Ежемесячно'),
    ]

    STATUS_CHOICES = [
        ('CREATED', 'Создана'),
        ('LAUNCHED', 'Запущена'),
        ('COMPLETED', 'Завершена')

    ]

    # Рассылка
    name = models.CharField(max_length=150, verbose_name='Название')
    send_time = models.TimeField(default=datetime.now, verbose_name='Время рассылки')
    start_date = models.DateField(default=date.today, verbose_name='Дата начала')
    end_date = models.DateField(default=date.today, verbose_name='Дата окончания')
    periodicity = models.CharField(max_length=50, choices=FREQUENCY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='CREATED', verbose_name='Статус')
    author = models.ForeignKey(users.models.User, on_delete=models.CASCADE, verbose_name='автор', **NULLABLE)
    message = models.ForeignKey(Message, verbose_name='сообщение', on_delete=models.CASCADE, **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name='клиенты', **NULLABLE)
    last_run = models.DateField(verbose_name='дата последней отправки рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('name',)
        permissions = [
            ('deactivate_mailing',
             'Deactivate_mailing',)
        ]




class Attempt(models.Model):
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    # Попытка рассылки
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    last_attempt = models.DateTimeField(verbose_name='Дата последней попытки', **NULLABLE)
    status = models.CharField(max_length=50, choices=STATUS, default=NOT_DELIVERED, verbose_name='статус')
    server_code = models.CharField(max_length=50, verbose_name='Ответ сервера', **NULLABLE)

    def __str__(self):
        return f'{self.mailing}'

    class Meta:
        verbose_name = 'попытка рассылки'
        verbose_name_plural = 'попытки рассылки'
        ordering = ('mailing',)

main/forms.py
from django import forms
from main.models import Mailing, Client

class FormStyleMixin:
    def __int__(self, *args, **kwargs):
        super().__int__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Mailing
        exclude = ['last_run']


class ClientForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Client
        fields = "__all__"

main/views.py
from django.shortcuts import redirect
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.urls import reverse_lazy, reverse
from main.models import Mailing, Client, Message
from blog.models import Blog
from main.forms import MailingForm, ClientForm
from main.services import send_manager


class HomeView(generic.TemplateView):
    template_name = 'main/homepage.html'

    def get_context_data(self, **kwargs):
        blog = Blog.objects.order_by('?')[:3]
        clients_count = len(Client.objects.all())  # кол-во клиентов
        mailing_count = len(Mailing.objects.all())  # кол-во рассылок
        mailing_active = len(Mailing.objects.filter(status='LAUNCHED'))  # кол-во активных рассылок
        context = super().get_context_data()
        context['mailing_count'] = mailing_count
        context['mailing_active'] = mailing_active
        context['clients_count'] = clients_count
        context['blogs'] = blog

        return context

class MailingListView(LoginRequiredMixin, generic.ListView):
    model = Mailing


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Mailing
    permission_required = 'main.view_mailing'

    def test_func(self):
        """Находится ли в группе managers или создатель"""
        obj = self.get_object()
        return self.request.user == obj.author or self.request.user.groups.filter(name='managers').exists()

class MailingCreateView(LoginRequiredMixin, generic.CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('main:mailing_list')
    #fields = ('name', 'send_time', 'start_date', 'end_date', 'periodicity', 'author')

    def form_valid(self, form):
        instance = form.save()
        instance.author = self.request.user

        send_manager()

        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Mailing

    success_url = reverse_lazy('main:mailing_list')
    permission_required = 'main.delete_mailing'


class MailingUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'main/mailing_form.html'
    success_url = reverse_lazy('main:mailing_list')


class ClientListView(LoginRequiredMixin, generic.ListView):
    model = Client


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = Client
    permission_required = 'main.view_client'


class ClientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        instance = form.save()
        instance.author = self.request.user
        return super().form_valid(form)

class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Client

    success_url = reverse_lazy('main:mailing_list')
    permission_required = 'main.delete_client'


class ClientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('main:client_list')


class MessageListView(LoginRequiredMixin, generic.ListView):
    model = Message


class MessageDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = Message
    permission_required = 'main.view_message'


class MessageCreateView(LoginRequiredMixin, generic.CreateView):
    model = Message
    success_url = reverse_lazy('main:message_list')
    fields = ('theme', 'content')

class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Message

    success_url = reverse_lazy('main:message_list')
    permission_required = 'main.delete_message'


class MessageUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Message
    success_url = reverse_lazy('main:message_list')


@permission_required('main.deactivate_mailing')
def deactive_mailing(request, pk):
    #Отключить рассылку

    obj = Mailing.objects.get(pk=pk)

    if (obj.status == 'CREATED') or (obj.status == 'LAUNCHED'):
        obj.status = 'COMPLETED'
        obj.save()

    return redirect(reverse('main:mailing_list'))

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <style>
        main {
            margin-top: 25px;
        }
    </style>
</head>
<main>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarCollapse">
              {% include 'main/includes/inc_menu.html' %}
          </div>
        </div>
      </nav>
    </header>
</main>

<body>
    <main role="main">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html'%}


{% block content %}
   <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены что хотите удалить запись "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:client_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html'%}

{% block content %}
    <div class="card-body">

        <h1>{{ mailing.email }}</h1>
        <p class="card-text">{{ mailing.mailings }}</p>

        <div class="card-footer">
            <a href="{% url 'main:client_list' %}" class="btn btn-primary"><< Назад</a>
        </div>>
    </div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html'%}

{% block content %}

        <form class="row" method="post">
            <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if client %}Сохранить{% else %} Создать {% endif %}">

                <div class="card-footer">
                    <a href="{% url 'main:client_list' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        <div class="col-6">
            <div class="card">
               <div class="card-header">
                   Клиенты
               </div>
            </div>
        </div>
    </form>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html'%}

{% block content %}
    {% if user.is_authenticated %}
    <div class="col-12">
        <a href="{% url 'main:client_create' %}" class="btn btn-primary m-2">Создать запись</a>
    </div>
    {% endif %}
    {% for client in client_list %}
        {% include 'main/includes/inc_client_card.html' %}
    {% endfor %}
{% endblock %}

main/templates/main/homepage.html
{% extends 'main/base.html'%}
{% load mediapath %}
{% block content %}
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">Всего рассылок: {{mailing_count}}</p>
            <p class="card-text">Активных рассылок: {{mailing_active}}</p>
            <p class="card-text">Количество клиентов: {{clients_count}} </p>

        </div>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - сервис рассылок</p>
    </div>

    <div class="container">
        <div class="row text-center">
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">$ 140</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- Неограниченная лицензия</li>
                            <li>- Поддержка</li>
                            <li>- Установка на сервер</li>
                            <li>- Получение обновлений</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{%for blog in blogs%}
    <div class="card shadow-sm">
        <div class="card-body">

            <img src="{% mediapath blog.img %}" alt="Картинка"  width="50" height="50"/>
            <h1>{{ blog.header }}</h1>
            <p class="card-text">{{ blog.content }}</p>
            <p class="card-text">{{ blog.views }}</p>
            <p class="card-text">{{ blog.date }}</p>

        </div>
    </div>
{%endfor%}

{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html'%}


{% block content %}
   <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены что хотите удалить запись "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:mailing_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html'%}

{% block content %}
    <div class="card-body">

        <h1>{{ mailing.name }}</h1>
        <p class="card-text">{{ mailing.send_time }}</p>
        <p class="card-text">{{ mailing.periodicity }}</p>
        <p class="card-text">{{ mailing.status }}</p>


        {% if perms.main.deactive_mailing %}
            <p><a href="{% url 'main:deactive_mailing' object.pk %}" class="btn btn-danger">Отключить </a></p>
         {%endif%}
        <div class="card-footer">
            <a href="{% url 'main:mailing_list' %}" class="btn btn-primary"><< Назад</a>
        </div>>
    </div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html'%}

{% block content %}

        <form class="row" method="post">
            <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if mailing %}Сохранить{% else %} Создать {% endif %}">

                <div class="card-footer">
                    <a href="{% url 'main:mailing_list' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        <div class="col-6">
            <div class="card">
               <div class="card-header">
                   Рассылки
               </div>
            </div>
        </div>
    </form>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html'%}

{% block content %}
    {% if user.is_authenticated %}
    <div class="col-12">
        <a href="{% url 'main:mailing_create' %}" class="btn btn-primary m-2">Создать запись</a>
    </div>
    {% endif %}
    {% for mailing in mailing_list %}
        {% include 'main/includes/inc_mailing_card.html' %}
    {% endfor %}
{% endblock %}

main/templates/main/message_confirm_delete.html
{% extends 'main/base.html'%}


{% block content %}
   <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены что хотите удалить запись "{{ object }}"?<br>
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:message_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/base.html'%}

{% block content %}
    <div class="card-body">

        <h1>{{ message.theme }}</h1>
        <p class="card-text">{{ message.content }}</p>
        <p class="card-text">{{ message.mailing }}</p>


        <div class="card-footer">
            <a href="{% url 'main:message_list' %}" class="btn btn-primary"><< Назад</a>
        </div>>
    </div>
{% endblock %}

main/templates/main/message_form.html
{% extends 'main/base.html'%}

{% block content %}

        <form class="row" method="post">
            <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if mailing %}Сохранить{% else %} Создать {% endif %}">

                <div class="card-footer">
                    <a href="{% url 'main:message_list' %}" class="btn btn-primary"><< Назад</a>
                </div>
            </div>
        <div class="col-6">
            <div class="card">
               <div class="card-header">
                   Сообщения
               </div>
            </div>
        </div>
    </form>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html'%}

{% block content %}
    {% if user.is_authenticated %}
    <div class="col-12">
        <a href="{% url 'main:message_create' %}" class="btn btn-primary m-2">Создать запись</a>
    </div>
    {% endif %}
    {% for message in message_list %}
        {% include 'main/includes/inc_message_card.html' %}
    {% endfor %}
{% endblock %}